import { promises as fs } from 'node:fs';
import { join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { ResolvedSkillsMcpOptions } from './types.js';
import { getMimeType, isTextMimeType, normalizeFilePath } from './utils.js';

const MANAGED_BLOCK_START = '# astro-skills:start';
const MANAGED_BLOCK_END = '# astro-skills:end';
const CACHE_CONTROL = 'public, max-age=3600';

interface StaticHeadersOptions {
	mcp: ResolvedSkillsMcpOptions | null;
}

interface HeaderEntry {
	path: string;
	headers: Array<[string, string]>;
}

export async function writeStaticHeaders(
	dir: URL,
	options: StaticHeadersOptions,
): Promise<number> {
	const outDir = fileURLToPath(dir);
	const roots = [
		{
			prefix: '/.well-known/agent-skills',
			directory: join(outDir, '.well-known', 'agent-skills'),
		},
	];

	if (options.mcp) {
		roots.push({
			prefix: options.mcp.prefix,
			directory: join(outDir, ...options.mcp.prefix.split('/').filter(Boolean)),
		});
	}

	const entries: HeaderEntry[] = [];
	for (const root of roots) {
		const files = await listFiles(root.directory);
		for (const file of files) {
			const relativePath = normalizeFilePath(relative(root.directory, file));
			entries.push(createHeaderEntry(`${root.prefix}/${relativePath}`, relativePath));
		}
	}

	if (entries.length === 0) return 0;

	const headersPath = join(outDir, '_headers');
	const existing = await fs.readFile(headersPath, 'utf-8').catch(() => '');
	const next = mergeManagedBlock(existing, renderHeaders(entries));
	await fs.writeFile(headersPath, next);

	return entries.length;
}

async function listFiles(directory: string): Promise<string[]> {
	const entries = await fs.readdir(directory, { recursive: true, withFileTypes: true }).catch(() => []);

	return entries
		.filter((entry) => entry.isFile())
		.map((entry) => join('parentPath' in entry ? entry.parentPath : directory, entry.name))
		.sort((a, b) => a.localeCompare(b));
}

function createHeaderEntry(path: string, relativePath: string): HeaderEntry {
	const contentType = getContentType(relativePath);
	const headers: Array<[string, string]> = [
		['Content-Type', contentType],
		['Cache-Control', CACHE_CONTROL],
	];

	if (relativePath.endsWith('.tar.gz')) {
		headers.push(['Content-Encoding', 'identity']);
	}

	return { path, headers };
}

function getContentType(path: string): string {
	const mimeType = getMimeType(path);
	return isTextMimeType(mimeType) ? `${mimeType}; charset=utf-8` : mimeType;
}

function renderHeaders(entries: HeaderEntry[]): string {
	return [
		MANAGED_BLOCK_START,
		'# Generated by astro-skills for static hosts that read _headers files.',
		...entries.flatMap((entry) => [
			entry.path,
			...entry.headers.map(([name, value]) => `  ${name}: ${value}`),
			'',
		]),
		MANAGED_BLOCK_END,
	].join('\n');
}

function mergeManagedBlock(existing: string, block: string): string {
	const normalizedBlock = `${block.trimEnd()}\n`;
	const start = existing.indexOf(MANAGED_BLOCK_START);
	const end = existing.indexOf(MANAGED_BLOCK_END);

	if (start !== -1 && end !== -1 && end > start) {
		const before = existing.slice(0, start).trimEnd();
		const after = existing.slice(end + MANAGED_BLOCK_END.length).trimStart();
		return [before, normalizedBlock, after].filter(Boolean).join('\n\n');
	}

	if (!existing.trim()) {
		return normalizedBlock;
	}

	return `${existing.trimEnd()}\n\n${normalizedBlock}`;
}
